language: c

os:
  - linux

compiler:
  - clang
  - gcc

script:
  - mkdir build
  - cd build
  - cmake -DOPENSSL_ROOT_DIR=/usr/local ..
  - make install
  - cd ..
  - rm -rf build

before_install:
  - sudo apt-get install -y curl
  - sudo apt-get install -y openssl
